[project]
name = "env01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "rdkit>=2024.9.6",
]
